### ISSUE TITLE
[IIIF Player] Add support for captions

### ISSUE THREAD

**Issue by Dananji** [avalonmediasystem/react-iiif-media-player#25]
### Description

Add captions support like in Avalon player;
![Screenshot from 2020-03-02 11-16-17.png](https://images.zenhubusercontent.com/5cc1c66b3244e00362de97ea/b2d0316e-a509-430d-9150-2699f653ad8b)

### Done Looks Like

iiif-player gives the user the ability to show and hide captions

**Comment by joncameron** [comment]
This will take some research and modeling--what does this look like inside the manifest? Do we supply this in the manifest right now? (no) The player should support it if present.

For the moment, looking at using the VTT as a resource. Mapping VTT to annotations is the ideal.
