### ISSUE TITLE
[IIIF Player] Parse section/structure labels properly

### ISSUE THREAD

**Issue by Dananji** [avalonmediasystem/react-iiif-media-player#29]
### Description

When the IIIF player parses the structure from manifest some labels are not parsed properly.

![Screenshot from 2020-03-02 11-39-27.png](https://images.zenhubusercontent.com/5cc1c66b3244e00362de97ea/ba78853a-ffb8-4242-96b7-d2962912e865)

### Done Looks Like

Each section and structure label should be parsed properly

**Comment by joncameron** [comment]
For the purposes of this issue we won't be needing to look at handling multiple languages or values per label.

**Comment by Dananji** [comment]
This was fixed in the work done in #27
