### ISSUE TITLE
[IIIF Player] Add support to load external manifests in GitHub demo

### ISSUE THREAD

**Issue by Dananji** [avalonmediasystem/react-iiif-media-player#43]
### Description

Add a field to load external manifests in GitHub demo page. An input field will take a URL for a manifest and render the player from it.

### Done Looks Like

A component to input URL of an external manifest.

### Notes

Should we support file uploads? 
A: Yes, if possible. Providing support for a user-provided file rather than a URI would be a nice QoL feature. We can come back and add another issue for this if needed.

**Comment by cjcolvar** [comment]
I think this is a great idea!  I don't think we need to handle any uploads and manifests will just need to be fetch-able with proper CORS headers just like for other IIIF clients.
