### ISSUE TITLE
Community sprint to create a full suite components package for React IIIF Media Player

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/react-iiif-media-player#57]
## Description
This document outlines collaborative work for sprint(s) intended to push the IIIF Media Player further so that it can integrate fully into the Avalon (or any) React application.  The primary goals would be to create individual wrapper components for each of the following:

- Media element player
- Playlists
- Lil scrubber
- ?

## Timeline
Fall 2020, November 16-27.

#### Previous note on planning
Assuming the work could be done in some type of sprint fashion where Northwestern's contributions could aim for 50% weekly work time for 2, 2-week sprints (4 weeks total) to kick it into gear?

It'd be a good opportunity to make this a Samvera community sprint also?   If any developers would possibly use the IIIF Media player solution in their stack, and are looking for some good intro React project experience.

I would be happy to lead the sprint's organization, resourcing and top-level architecture.  

## Goals
- After completion of both sprints, a minimal, skeleton solution is available as importable React components from an Github branch.
- Avalon has a branch which can support the MVP solution
- Any generic, starter React project can import the MVP and interact with a mock API to support player and component interactions.
- Documentation is written
- Next steps are documented for how to complete the work.

To accomplish this, the work would roughly fall into these categories

### Refactor current bundling/dev environment 
Use: https://github.com/samvera-labs/starter-react-component-npm
- sub issue 
- sub issue

### Refactor Class based components
To future-proof the application, we should refactor all components away from Class-based components and use functional components and React Hooks.

### Define API for communication to/from the player and it's components
In order for the player and it's components to integrate within an application, an API must be defined which supports POST and GET network requests.

This could initially take the shape of a mock API service.

Avalon would also want to ensure its app's API supports all interactions.

### Write a wrapper around Manifesto package
So parsing of the manifest can be more easily tested, might need to write some wrapper code around Manifesto so the parsing can be tested. See [Mirador](https://github.com/ProjectMirador/mirador) for examples.

### Build out components
- Use existing CSS package (ie. Bootstrap), or customize CSS?
- This would be a large portion of the work... more details to follow

### Documentation
Documentation can be provided by Styleguidist if we refactor the bundling / dev environment to use:  https://github.com/samvera-labs/starter-react-component-npm

This should be an important step along the way to document each exported component along with code examples for integration.   Hopefully the Styleguidist dev environment would support the increasingly complex interactions...assuming it'd be ok but if not we can set up a Rollup dev environment and handle documentation another way.

**Comment by adamjarling** [comment]
@phuongdh @Dananji @joncameron @mcwhitaker @davidschober  If you'd all like to take a look through the text above and let us know your thoughts?

**Comment by mcwhitaker** [comment]
@adamjarling  - Thank you for this, and thank you, @davidschober for the idea of a community sprint. 

Fall 2020 sounds good. If NU will not be available for a while, we would probably start with @Dananji doing some work on her own. The change from class-based components to functional components addresses our goal of having the multiple player functions in separate components so we don't have to take all or nothing. And we can also place them on a page in different locations, which was also part of our motivation to separate things.

@Dananji says that your new version of the boiler plate has significant improvements over the last version she had seen. She can start moving as time allows, maybe discussing with you first steps to not complicate the community sprint later.

**Comment by adamjarling** [comment]
@Dananji @mcwhitaker So after chatting with @davidschober a bit on this, what if the general timeline for community work was as follows?

- Now through Samvera Connect: prep work & plan out goals / timeline
- Call for volunteers at Samvera Connect
- Propose & develop the project at Samvera Connect Dev Congress
- Fill out schedule through rest of the calendar year

I know this is pretty loose, but our team is focused on an application launch targeting November 13th, which has been a long time in the works.

Does this sound reasonable?  If so, maybe we schedule another meeting in the next 2 weeks to get down more of what the final deliverables look like for the player for both our teams?

**Comment by mcwhitaker** [comment]
@adamjarling  I think the outline is good. Connect is a good opportunity to enlist help, also. 

@Dananji  has done some work on our end to define the work from our perspective. You can check our Zen board, Epic "IIIF Player".  We can talk about this and your needs in this meeting you are proposing for sometime in the next 2 weeks.

Do you want me to create a doodle for this meeting? Are there better times for your team? I can look at our calendars and propose some options.

**Comment by adamjarling** [comment]
Hey @mcwhitaker Yea a Doodle poll would be great.  Generally late morning / early afternoon might be best?

**Comment by mcwhitaker** [comment]
@adamjarling  Late morning for you is lunch time for us. Early afternoon for us is lunch time for you. I will do what I can!

**Comment by mcwhitaker** [comment]
@adamjarling @davidschober  - I posted a doodle poll link yesterday in the avalon-core channel, but maybe you silenced that channel so here it is: https://doodle.com/poll/bazefif3wgcqpf7b

Please invite others from NU to fill out the poll that you think need to be there.
