### ISSUE TITLE
IIIF Auth Implementation in Avalon IIIF Player

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/react-iiif-media-player#7]
## Description 

The IIIF player should be able to work with IIIF auth and respond accordingly. 

## Done looks like

- an end user is able to authenticate and see IIIF auth protected content
- public works are visible

### Notes
- This has been implemented in the Timeliner. We should be able to take that code and apply it here.

Child of https://github.com/samvera-labs/avalon-bundle/issues/305

**Comment by Dananji** [comment]
@mcwhitaker Where can I find IIIF auth protected content? Would anything on mco-staging or any other IU instance that are not public work?

**Comment by mcwhitaker** [comment]
@Dananji  Yes, anything that is not public.

**Comment by Dananji** [comment]
I was not able to open this manifest from mco-staging, https://mco-staging.dlib.indiana.edu/media_objects/9z9036572/manifest.json on https://iiif-timeliner.netlify.app/. It is giving me 401.

**Comment by mcwhitaker** [comment]
@Dananji I am not sure the netlify version is good for this. Maybe try the timeliner.dlib.indiana.edu tool, but in that case you will need to put the manifest on maple for the CORS support that this site requires.

**Comment by phuongdh** [comment]
We may need to add iiif-timeliner domain to the Wowza security goodlist in order to fetch the m3u8 file directly..

**Comment by mcwhitaker** [comment]
Given that the iiif community will start working on a new spec for auth as a consequence of the problems with browsers not allowing cross-site cookies, the current strategy will become obsolete soon. We are abandoning this ticket for now.
