### ISSUE TITLE
Establish unit testing pattern for new app structure

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/react-iiif-media-player#73]
### Description
As the entire application is shifting, we'll need to establish a new pattern or two for how to structure Jest unit tests w/ Testing Library.   

### Done looks like
- [ ] Remove any unnecessary test dependencies
- [ ] Create a pattern for mocking the new `Provider` components we're wrapping the application code with

**Comment by joncameron** [comment]
Completed
