### ISSUE TITLE
Package IIIF player for use in Hyrax/Avalon Bundle

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/react-iiif-media-player#8]
### Description

The IIIF player should be packaged in the same way as the Structural Metadata Editor. Packaging workflow and lessons learned from that should be used for the IIIF player. 

### Done Looks Like
- Agreed upon packaging solution is used for the Avalon IIIF Player.

#### Notes
The IIIF player has had a one-time packaging strategy applied, but we need a better solution where continued development on IIIF player is smooth and easy to work into Avalon.

Blocked until an agreed upon packaging strategy is developed as part of Structural Metadata Editor discussion/work.

child of https://github.com/samvera-labs/avalon-bundle/issues/305

**Comment by adamjarling** [comment]
@davidschober Looks like this one is a duplicate as well. #9

**Comment by davidschober** [comment]
Two for the price of one! closing as dupe.
